id: ced3c179866741d990235ebbac367138
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_312-Entering_the_City_of_Vaisali-v2
  language: en
  author: ''
  volume: {}
